services:
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - techlab_net
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  frontend_backoffice:
    build:
      dockerfile: frontend-backoffice.Dockerfile
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    networks:
      - techlab_net

  frontend_chat:
    build:
      dockerfile: frontend-chat.Dockerfile
    environment:
      - PORT=8082
    ports:
      - 8082:8082
    networks:
      - techlab_net

  backend_1:
    build:
      dockerfile: backend.Dockerfile
    links:
      - database
    # command: yarn workspace techlab-challenge-2024-3q-backend typeorm migration:run
    environment:
      - APP_PORT=8000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/database
      - SECRET="23345dgfdjhnfgbjuy"
      # - DATABASE_MIGRATIONS_RUN=true
    networks:
      - techlab_net
    depends_on:
      - database

  backend_2:
    build:
      dockerfile: backend.Dockerfile
    links:
      - database
    environment:
      - APP_PORT=8000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/database
      - SECRET="23345dgfdjhnfgbjuy"
    networks:
      - techlab_net
    depends_on:
      - database

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:8000
    networks: 
      - techlab_net
    depends_on:
      - backend_1
      - backend_2
    links:
      - backend_1
      - backend_2

volumes: 
  mongodb_data:
    driver: local
networks:
  techlab_net:
    driver: bridge